// A small pill marking content as an AI suggestion — advisory, not a verdict.
// Uses the same purple accent as AI-inferred graph edges so AI output reads consistently.
export function AiSuggestionBadge({ className = '' }: { className?: string }) {
  return (
    <span
      title="Generated by AI to guide your review — not verified"
      className={`inline-flex items-center rounded border border-purple-300 bg-purple-50 px-1.5 py-0.5 text-[11px] font-medium text-purple-700 dark:border-purple-700 dark:bg-purple-950/40 dark:text-purple-300 ${className}`}
    >
      AI suggestion
    </span>
  );
}
